version: "3"

services:
  jenkins:
    user: jenkins      
    image: jenkins/jenkins
    container_name: jenkins
    ports:
     - 8080:8080
     - 5000:5000
    volumes:
      - /home/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    
  sonar:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - 9000:9000
    volumes:
      - /home/sonarqube/data:/opt/sonarqube/data
    restart: on-failure


  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - 8081:8081
      
    volumes:
      - /home/nexus/nexus-data:/sonatype-work
    restart: on-failure
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
