version: "3"

services:
  jenkins:
    user: jenkins      
    image: jenkins/jenkins
    container_name: jenkins
    ports:
     - 8080
    volumes:
      - /data/jenkins
    restart: on-failure
    
  sonar:
    image: sonarqube:latest
    container_name: sonar
    ports:
      - 9000
    volumes:
      - /data/sonar
    restart: on-failure


  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - 8081
      
    volumes:
      - /data/nexus
    restart: on-failure
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
